### ISSUE TITLE
Fix cast of ifstream to bool

### ISSUE THREAD

**Issue by alberto-santini** [ryanrossi/pmc#3]
In `pmc_utils.cpp`, in function `fexists` you are returning an `std::ifstream` where a `bool` is needed.
The code won't compile with GCC 8.2.0:

```
pmc_utils.cpp: In function ‘bool fexists(const char*)’:
pmc_utils.cpp:26:12: error: cannot convert ‘std::ifstream’ {aka ‘std::basic_ifstream<char>’} to ‘bool’ in return
     return ifile;
            ^~~~~
```

A simple fix could be to replace `return ifile;` with `return !ifile.fail();`.

**Comment by carcarmor** [comment]
I was having the same issue when compiling and changing `return ifile;` with `return !ifile.fail();` in `pmc_utils.cpp` solved the problem. Thanks for your post!
